version: "3"
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80"
    networks:
      - backend
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - mysql
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=WORDPRESS]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints: [node.role == manager]
  mysql:
      image: mysql:5.7
      networks:
        backend:
          aliases:
            - db
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
      deploy:
        placement:
          constraints: [node.role == worker]

networks:
  backend: